name: Cypress API Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instala Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instala dependências
        run: npm ci

      - name: Executa os testes
        run: npx cypress run --e2e

      - name: Gera relatório mochawesome
        if: always()
        run: |
          mkdir -p artifacts
          cp -r cypress/reports artifacts/

      - name: Publica relatório como artefato
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: artifacts
